# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- main

name: $(Date:yyyyMMdd)$(Rev:.r)

stages:
  - stage: TestPipelineDevops
    displayname:"Test Pipeline devops with a simple python scprit"
    variables:
      - name: BuildURL
        value: $(System.TeamFoundationCollectionUri)$(System.TeamProject)/_build/results?buildId=$(Build.BuildId)

    jobs:
    - job: Test
      displayName: 'Test the application'
      pool:
        name: Default


    steps:
      - script: pip install -r requirements.txt
        displayName: 'Install requirements'
      - script: echo $(buildURL)
      - script: python3 test.py